reddit:
  subreddits:
    - Unexpected
    - AbruptChaos
    - PublicFreakout
    - AnimalsBeingDerps
  min_upvotes: 5000
  max_duration_seconds: 90

shorts:
  clip_min_seconds: 20
  clip_max_seconds: 40

posting:
  uploads_per_run: 1
